export const GameConstant = Object.freeze({
  PLATFORM_ANDROID: "Android",
  PLATFORM_IOS: "iOS",

  GAME_WIDTH: 720,
  GAME_HEIGHT: 1280,

  SCENE_PLAY: "PlayScene",
  SCENE_END_CARD: "EndCardScene",

  DEBUG_ON: true,
  DEBUG_DRAW_COLLIDER: false,
  SOUND_ENABLED: true,
  SHOW_GAME_TAG: false,

  GAME_LIFE: 1,
  BACKGROUND_SPEED: 100,
  BULLET_BOUND_OFFSET: 100,
  SWIPE_MULTIPLIER: 1,
  AUTO_CTA_DELAY: 7,
  PLAYER_REVIVE_IMMORTAL_DURATION: 1,

  SHIP_SPEED: 15,
  SHIP_HP: 50,
  SHIP_IMMORTAL: false,
  SHIP_PURPLE_BULLET_DAMAGE: 10,
  SHIP_GREEN_BULLET_DAMAGE: 5,
  SHIP_WINGS_DURATION: 10,
  SHIP_FX_IMMORTAL_DURATION: 0.35,

  BULLET_LASER_DPS: 50,
  BULLET_FROST_DAMAGE: 10,

  BOOSTER_MAGNET_SIZE: 800,
  BOOSTER_MAGNET_SPEED: 800,

  WAVE_1_ENEMY_HP: 60,
  WAVE_2_ENEMY_HP: 600,
  WAVE_3_ENEMY_HP: 100,

  WAVE_4_ENEMY_HP: 10,
  WAVE_4_BOSS_HP: 40,
  WAVE_4_ENEMY_SPEED_INCREAMENT: 4,

  WAVE_5_ENEMY_SPEED: 370,
  WAVE_5_ENEMY_HP: 10,

  REDUCE_SIZE_SHIP: 0.8,
  ENEMY_SIZE: 1,
  WAVE_7_MOVE_DURATION: 13,
  WAVE_7_MOVE_SPEED: 150,
});
